config/routes.rb
Rails.application.routes.draw do
  root "static_pages#welcome"
  get "welcome" => "static_pages#welcome"

  get "workspace" => "m_workspaces#new"

  get "signin" => "sessions#new"
  post "signin" => "sessions#create"

  get "change_password" => "change_password#new"

  post "profile_upload" => "m_users#profile_upload"

  get "home" => "static_pages#home"

  get "memberinvite" => "member_invitation#new"
  post "memberinvite" => "member_invitation#invite"
  get "confirminvitation" => "m_users#confirm"

  get "channelcreate" => "m_channels#new"
  post "channelcreate" => "m_channels#create"

  get "channeledit" => "m_channels#edit"
  get "delete_channel" => "m_channels#delete"
  post "channelupdate" => "m_channels#update"

  get "star" => "t_direct_star_msg#create"
  get "unstar" => "t_direct_star_msg#destroy"
  get "starthread" => "t_direct_star_thread#create"
  get "unstarthread" => "t_direct_star_thread#destroy"

  get "delete_directmsg" => "direct_message#deletemsg"
  get "delete_directthread" => "direct_message#deletethread"

  get "delete_groupmsg" => "group_message#deletemsg"
  get "delete_groupthread" => "group_message#deletethread"

  get "groupstar" => "t_group_star_msg#create"
  get "groupunstar" => "t_group_star_msg#destroy"
  get "groupstarthread" => "t_group_star_thread#create"
  get "groupunstarthread" => "t_group_star_thread#destroy"

  get "starlists" => "star_lists#show"
  get "thread" => "thread#show"
  get "mentionlists" => "mention_lists#show"
  get "allunread" => "all_unread#show"
  get "draftlists" => "draft_lists#show"

  get "usermanage" => "user_manage#usermanage"
  get "edit" => "user_manage#edit"
  get "update" => "user_manage#update"

  get "channeluser" => "channel_user#show"
  get "channeluseradd" => "channel_user#create"
  get "channeluserdestroy" => "channel_user#destroy"
  get "channeluserleave" => "channel_user#leave"
  get "channeluserjoin" => "channel_user#join"

  post 'directmsg' => 'direct_message#show'
  post 'directthreadmsg' => 'direct_message#showthread'
  post 'directthreadmsgdirectly' => 'direct_message#showthreaddirectly'
  
  post 'groupmsg' => 'group_message#show'
  post 'groupthreadmsg' => 'group_message#showthread'
  post 'groupthreadmsgdirectly' => 'group_message#showthreaddirectly'

  get "refresh" => "sessions#refresh"

  get "refresh_direct" => "m_users#refresh_direct"
  get "refresh_group" => "m_channels#refresh_group"

  delete 'logout' =>  'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  # edit username
  get "useredit" => "m_users#edituser"
  patch "useredit" => "m_users#updateuser"

  # edit direct message
  get "/directmsg/edit/:id" => "direct_message#edit", as: "edit_directmsg"
  post "update_directmsg" => "direct_message#update"
  # edit direct thread
  get "/directthreadmsg/edit/:id" => "direct_message#edit_thread", as: "edit_directthreadmsg"
  post "update_directthreadmsg" => "direct_message#update_thread"
  # edit group message
  get "/groupmsg/edit/:id" => "group_message#edit", as: "edit_groupmsg"
  post "update_groupmsg" => "group_message#update"
  # edit group thread
  get "/groupthreadmsg/edit/:id" => "group_message#edit_thread", as: "edit_groupthreadmsg"
  post "update_groupthreadmsg" => "group_message#update_thread"

  # start routes for direct react
  post "directreact" => "t_direct_react_msg#create"
  get "directreact" => "t_direct_react_msg#create"

  post "directthreadreact" => "t_direct_react_thread#create"
  get "directthreadreact" => "t_direct_react_thread#create"
  # end routes for direct react

  # start routes for group react
  post "groupreact" => "t_group_react_msg#create"
  get "groupreact" => "t_group_react_msg#create"

  post "groupthreadreact" => "t_group_react_thread#create"
  get "groupthreadreact" => "t_group_react_thread#create"
  # end routes for group react

  resources :m_workspaces
  resources :m_users
  resources :m_channels
  resources :t_direct_messages
  resources :t_group_messages
end

app/models/m_channel.rb
class MChannel 
  include ActiveModel::Model

  attr_accessor :channel_name
  attr_accessor :channel_status
  attr_accessor :m_workspace_id
  attr_accessor :created_at
  attr_accessor :updated_at

end

app/controllers/m_channels_controller.rb
class MChannelsController < ApplicationController
  include FaradayApiClient
  before_action :check_token
  def new
    #check unlogin user

    session.delete(:s_user_id)
    session.delete(:s_channel_id)
    session.delete(:s_direct_message_id)
    session.delete(:s_group_message_id)

    retrievehome
  end

  def refresh_group
    if session[:r_group_size].nil?
      session[:r_group_size] =  10
    else
      session[:r_group_size] +=  10
    end

    #call from ApplicationController for retrieve group message data
    retrieve_group_message

    #call from ApplicationController for retrieve home data
    retrievehome
  end

  def create
    #check unlogin user

    #call from ApplicationController for retrieve home data
    retrievehome

    if params[:session][:channel_name].nil? || params[:session][:channel_name] == ""
      flash[:danger] = "Channel Name can't be blank."
      render 'm_channels/new'
    else
      data = {
          "user_id": session[:current_user_id],
          "channel_status": params[:session][:channel_status],
          "channel_name": params[:session][:channel_name],
          "m_workspace_id": session[:workspace_id]
      }
      post_data('/m_channels',{m_channel: data})
      redirect_to home_url
    end
  end

  def show
    session.delete(:s_user_id)
    session.delete(:s_direct_message_id)
    session.delete(:s_group_message_id)
    session.delete(:r_direct_size)

    session[:s_channel_id] =  params[:id]

    session[:r_group_size] = 10

    retrieve_group_message

    retrievehome
  end

  def edit
    # @m_channel =  session[:s_channel_id]
    #call from ApplicationController for retrieve home data
    retrievehome 
    
    data = {
      "id": session[:s_channel_id]
    }
    response = get_data("/channeledit", data)
    @m_channel = response["m_channel"]
  end

  def update
    channel_status = params[:session][:channel_status]
    channel_name = params[:session][:channel_name]
    data = {
      "channel_status": channel_status ,
      "channel_name": channel_name ,
      "m_workspace_id": session[:workspace_id]
    }
    post_data("/channelupdate?id=#{session[:s_channel_id]}",{m_channel: data})

    redirect_to m_channel_path(session[:s_channel_id])
  end

  def delete
    channel_id =  session[:s_channel_id]
    delete_data("/m_channels/#{channel_id}")
    redirect_to home_url 
  end
end

app/helpers/m_channels_helper.rb
module MChannelsHelper
end

app/views/m_channels/edit.html.erb
<h2 class="style1" style="text-align:center">チャンネル変更</h2>
  <br><br>
  <div class="container para">
    <div class="col-md-6 col-md-offset-4">
      <%= form_for(:session, url: channelupdate_url) do |f| %>
        <%= f.hidden_field :id %>
        <div class="col-md-1">
          <% if @m_channel['channel_status'] == false %>
          <%= f.radio_button :channel_status,'false', :checked=>true  %> 
        </div>
        <div class="col-md-3">
          <%= f.label :プライベート %>
        </div>
        <div class="col-md-1">
          <%= f.radio_button :channel_status,'true' %>
        </div>
        <div class="col-md-3">
          <%= f.label :パブリック %>
        </div>
        <% else %>
          <%= f.radio_button :channel_status,'false' %> 
        </div>
        <div class="col-md-3">
          <%= f.label :プライベート %>
        </div>
        <div class="col-md-1">
          <%= f.radio_button :channel_status,'true',:checked=>true %>
        </div>
        <div class="col-md-3">
          <%= f.label :パブリック %>
        </div>

        <% end %>
        <br><br>

        <%= f.label :チャンネル名 %>
        <%= f.text_field:channel_name, class:'form-control', value: @m_channel['channel_name'] %> 
        <%= f.submit "変更", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
  <div>
    <%= render 'leftpanel/leftpanel' %>
  </div>

app/views/m_channels/new.html.erb
<div id="main">
<h2 class="style1" style="text-align:center">チャンネル作成</h2>
  <br><br>
  <div class="container para">
    <div class="col-md-6 col-md-offset-4">
      <%=form_for(:session, url: channelcreate_url) do |f| %>
        <div class="col-md-1">
        <%= f.radio_button :channel_status, '0', :checked => true %> 
        </div>
        <div class="col-md-3">
        <%= f.label :プライベート %>
        </div>
        <div class="col-md-1">
        <%= f.radio_button :channel_status, '1'%>
        </div>
        <div class="col-md-3">
        <%= f.label :パブリック %>
        </div>
        <br><br>

        <%= f.label :チャンネル名%>
        <%= f.text_field:channel_name, class:'form-control'%> 
        <%= f.submit "Create Channel", class: "btn btn-primary" %>
        <% end %>
    </div>
  </div>
                                
                                
                           
</div>
<div>
    <%= render 'leftpanel/leftpanel' %>
</div>


<script>
function openNav() {
  document.getElementById("mySidenav").style.width = "250px";
  document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
}
</script>

app/views/m_channels/refresh_group.html.erb
<%= render 'group_show/show' %>

app/views/m_channels/show.html.erb
<%= render 'group_show/show' %>