config/routes.rb
Rails.application.routes.draw do
  root "static_pages#welcome"
  get "welcome" => "static_pages#welcome"

  get "workspace" => "m_workspaces#new"

  get "signin" => "sessions#new"
  post "signin" => "sessions#create"

  get "change_password" => "change_password#new"

  post "profile_upload" => "m_users#profile_upload"

  get "home" => "static_pages#home"

  get "memberinvite" => "member_invitation#new"
  post "memberinvite" => "member_invitation#invite"
  get "confirminvitation" => "m_users#confirm"

  get "channelcreate" => "m_channels#new"
  post "channelcreate" => "m_channels#create"

  get "channeledit" => "m_channels#edit"
  get "delete_channel" => "m_channels#delete"
  post "channelupdate" => "m_channels#update"

  get "star" => "t_direct_star_msg#create"
  get "unstar" => "t_direct_star_msg#destroy"
  get "starthread" => "t_direct_star_thread#create"
  get "unstarthread" => "t_direct_star_thread#destroy"

  get "delete_directmsg" => "direct_message#deletemsg"
  get "delete_directthread" => "direct_message#deletethread"

  get "delete_groupmsg" => "group_message#deletemsg"
  get "delete_groupthread" => "group_message#deletethread"

  get "groupstar" => "t_group_star_msg#create"
  get "groupunstar" => "t_group_star_msg#destroy"
  get "groupstarthread" => "t_group_star_thread#create"
  get "groupunstarthread" => "t_group_star_thread#destroy"

  get "starlists" => "star_lists#show"
  get "thread" => "thread#show"
  get "mentionlists" => "mention_lists#show"
  get "allunread" => "all_unread#show"
  get "draftlists" => "draft_lists#show"

  get "usermanage" => "user_manage#usermanage"
  get "edit" => "user_manage#edit"
  get "update" => "user_manage#update"

  get "channeluser" => "channel_user#show"
  get "channeluseradd" => "channel_user#create"
  get "channeluserdestroy" => "channel_user#destroy"
  get "channeluserleave" => "channel_user#leave"
  get "channeluserjoin" => "channel_user#join"

  post 'directmsg' => 'direct_message#show'
  post 'directthreadmsg' => 'direct_message#showthread'
  post 'directthreadmsgdirectly' => 'direct_message#showthreaddirectly'
  
  post 'groupmsg' => 'group_message#show'
  post 'groupthreadmsg' => 'group_message#showthread'
  post 'groupthreadmsgdirectly' => 'group_message#showthreaddirectly'

  get "refresh" => "sessions#refresh"

  get "refresh_direct" => "m_users#refresh_direct"
  get "refresh_group" => "m_channels#refresh_group"

  delete 'logout' =>  'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  # edit username
  get "useredit" => "m_users#edituser"
  patch "useredit" => "m_users#updateuser"

  # edit direct message
  get "/directmsg/edit/:id" => "direct_message#edit", as: "edit_directmsg"
  post "update_directmsg" => "direct_message#update"
  # edit direct thread
  get "/directthreadmsg/edit/:id" => "direct_message#edit_thread", as: "edit_directthreadmsg"
  post "update_directthreadmsg" => "direct_message#update_thread"
  # edit group message
  get "/groupmsg/edit/:id" => "group_message#edit", as: "edit_groupmsg"
  post "update_groupmsg" => "group_message#update"
  # edit group thread
  get "/groupthreadmsg/edit/:id" => "group_message#edit_thread", as: "edit_groupthreadmsg"
  post "update_groupthreadmsg" => "group_message#update_thread"

  # start routes for direct react
  post "directreact" => "t_direct_react_msg#create"
  get "directreact" => "t_direct_react_msg#create"

  post "directthreadreact" => "t_direct_react_thread#create"
  get "directthreadreact" => "t_direct_react_thread#create"
  # end routes for direct react

  # start routes for group react
  post "groupreact" => "t_group_react_msg#create"
  get "groupreact" => "t_group_react_msg#create"

  post "groupthreadreact" => "t_group_react_thread#create"
  get "groupthreadreact" => "t_group_react_thread#create"
  # end routes for group react

  resources :m_workspaces
  resources :m_users
  resources :m_channels
  resources :t_direct_messages
  resources :t_group_messages
end

app/models/m_workspace.rb
class MWorkspace
  include ActiveModel::Model
  
  attr_accessor :workspace_name
  attr_accessor :created_at
  attr_accessor :updated_at
  
end

app/controllers/m_workspaces_controller.rb
class MWorkspacesController < ApplicationController
  include FaradayApiClient

  def new
  end
  
  def create
    remember_digest = params[:m_user][:remember_digest]
    profile_image = params[:m_user][:profile_image]
    name = params[:m_user][:name]
    email = params[:m_user][:email]
    password = params[:m_user][:password]
    password_confirmation = params[:m_user][:password_confirmation]
    admin = true 

    data = {
      remember_digest: remember_digest,
      profile_image: profile_image,
      name: name,
      email: email,
      password: password,
      password_confirmation: password_confirmation,
      admin: admin
    }

    result = post_data('/m_users', { m_user: data })

    if result.nil?
      flash.now[:danger] = 'User creation failed'
      render 'new'
    else
      # Check user deactivation status here
      flash.now[:success] = 'User has been successfully created'
      redirect_to signin_path
    end
  end
end

app/helpers/m_workspaces_helper.rb
module MWorkspacesHelper
end

app/views/m_workspaces/new.html.erb
<% provide(:title, 'Create Workspace') %>
<div id="password_error" class="text-danger style22" style="margin-left:280px; font-size:14px;"></div>
<h1>Create Workspace</h1>
<div class="container para">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for MUser.new, url: m_workspaces_path, html: { onclick: "return validateForm()" } do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :workspace_name, "Workspace Name" %>
      <%= f.text_field :remember_digest, class: 'form-control' %>

      <%= f.label :channel_name, "Channel Name" %>
      <%= f.text_field :profile_image, class: 'form-control' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control validatepwd' %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control validate_confirmpwd' %>

      <%= f.hidden_field :admin, value: '1', class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
      <div class="warning-message" style="color: #0077B6; margin-top: 10px;">
        <strong style="margin-bottom: 5px;">Password must contain at least 8 characters, 1 upper and lower case characters, 1 digit and 1 special character.</strong>
      </div>

    <% end %>
  </div>
</div>

<script>
  function validateForm() {
    const password = document.querySelector('.validatepwd').value;
    const password_confirmation = document.querySelector('.validate_confirmpwd').value;
    const password_err = document.getElementById('password_error');
    password_err.textContent = '';
    if (password != "" && password_confirmation != "") {
      if (!/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@\'#'$&*]).{8,}/.test(password) ) {
        password_err.textContent = "Password must be at least 8 characters long, contain at least one lowercase letter, one uppercase letter, one digit, and one special character.";
        return false;
      }
    }
    return true;
  }
</script>