config/routes.rb
Rails.application.routes.draw do
  root "static_pages#welcome"
  get "welcome" => "static_pages#welcome"

  get "workspace" => "m_workspaces#new"

  get "signin" => "sessions#new"
  post "signin" => "sessions#create"

  get "change_password" => "change_password#new"

  post "profile_upload" => "m_users#profile_upload"

  get "home" => "static_pages#home"

  get "memberinvite" => "member_invitation#new"
  post "memberinvite" => "member_invitation#invite"
  get "confirminvitation" => "m_users#confirm"

  get "channelcreate" => "m_channels#new"
  post "channelcreate" => "m_channels#create"

  get "channeledit" => "m_channels#edit"
  get "delete_channel" => "m_channels#delete"
  post "channelupdate" => "m_channels#update"

  get "star" => "t_direct_star_msg#create"
  get "unstar" => "t_direct_star_msg#destroy"
  get "starthread" => "t_direct_star_thread#create"
  get "unstarthread" => "t_direct_star_thread#destroy"

  get "delete_directmsg" => "direct_message#deletemsg"
  get "delete_directthread" => "direct_message#deletethread"

  get "delete_groupmsg" => "group_message#deletemsg"
  get "delete_groupthread" => "group_message#deletethread"

  get "groupstar" => "t_group_star_msg#create"
  get "groupunstar" => "t_group_star_msg#destroy"
  get "groupstarthread" => "t_group_star_thread#create"
  get "groupunstarthread" => "t_group_star_thread#destroy"

  get "starlists" => "star_lists#show"
  get "thread" => "thread#show"
  get "mentionlists" => "mention_lists#show"
  get "allunread" => "all_unread#show"
  get "draftlists" => "draft_lists#show"

  get "usermanage" => "user_manage#usermanage"
  get "edit" => "user_manage#edit"
  get "update" => "user_manage#update"

  get "channeluser" => "channel_user#show"
  get "channeluseradd" => "channel_user#create"
  get "channeluserdestroy" => "channel_user#destroy"
  get "channeluserleave" => "channel_user#leave"
  get "channeluserjoin" => "channel_user#join"

  post 'directmsg' => 'direct_message#show'
  post 'directthreadmsg' => 'direct_message#showthread'
  post 'directthreadmsgdirectly' => 'direct_message#showthreaddirectly'
  
  post 'groupmsg' => 'group_message#show'
  post 'groupthreadmsg' => 'group_message#showthread'
  post 'groupthreadmsgdirectly' => 'group_message#showthreaddirectly'

  get "refresh" => "sessions#refresh"

  get "refresh_direct" => "m_users#refresh_direct"
  get "refresh_group" => "m_channels#refresh_group"

  delete 'logout' =>  'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  # edit username
  get "useredit" => "m_users#edituser"
  patch "useredit" => "m_users#updateuser"

  # edit direct message
  get "/directmsg/edit/:id" => "direct_message#edit", as: "edit_directmsg"
  post "update_directmsg" => "direct_message#update"
  # edit direct thread
  get "/directthreadmsg/edit/:id" => "direct_message#edit_thread", as: "edit_directthreadmsg"
  post "update_directthreadmsg" => "direct_message#update_thread"
  # edit group message
  get "/groupmsg/edit/:id" => "group_message#edit", as: "edit_groupmsg"
  post "update_groupmsg" => "group_message#update"
  # edit group thread
  get "/groupthreadmsg/edit/:id" => "group_message#edit_thread", as: "edit_groupthreadmsg"
  post "update_groupthreadmsg" => "group_message#update_thread"

  # start routes for direct react
  post "directreact" => "t_direct_react_msg#create"
  get "directreact" => "t_direct_react_msg#create"

  post "directthreadreact" => "t_direct_react_thread#create"
  get "directthreadreact" => "t_direct_react_thread#create"
  # end routes for direct react

  # start routes for group react
  post "groupreact" => "t_group_react_msg#create"
  get "groupreact" => "t_group_react_msg#create"

  post "groupthreadreact" => "t_group_react_thread#create"
  get "groupthreadreact" => "t_group_react_thread#create"
  # end routes for group react

  resources :m_workspaces
  resources :m_users
  resources :m_channels
  resources :t_direct_messages
  resources :t_group_messages
end

app/controllers/channel_user_controller.rb
class ChannelUserController < ApplicationController
  include FaradayApiClient
  before_action :check_token
  def show
    response = get_data("/channeluser?channel_id=#{session[:s_channel_id]}&workspace_id=#{session[:workspace_id]}")
    @c_users_id = response['c_users_id'] || []
    retrieve_group_message
    retrievehome
  end

  def create
    user_id = params[:userid]
    get_data("/channeluserjoin?user_id=#{user_id}&channel_id=#{session[:s_channel_id]}")
    redirect_to channeluser_path
  end

  def join 
    user_id = session[:current_user_id]
    get_data("/channeluserjoin?user_id=#{user_id}&channel_id=#{session[:s_channel_id]}")
    redirect_to m_channel_path(id:session[:s_channel_id] )
  end

  def leave
    get_data("/channeluserdestroy?id=#{params[:id]}&channel_id=#{session[:s_channel_id]}")
    redirect_to home_url
  end

  def destroy
    get_data("/channeluserdestroy?id=#{params[:id]}&channel_id=#{session[:s_channel_id]}")
    puts"---------user#{params[:id]}------------channel#{session[:s_channel_id]} "
    redirect_to channeluser_path
  end
end

app/helpers/channel_user_helper.rb
module ChannelUserHelper
end

app/views/channel_user/show.html.erb
<div id="main">
  <div class = "txtmsg">	
    <% @count = 0 %>
      
    <div class="title" >			
      <h2 class="style1"><%= @s_channel["channel_name"]%></h2>
    </div>
    <div class="container" style="padding-top: 60px;">
      <% if @m_channelsids.include?session[:s_channel_id].to_i %>
        <div class="col-md-6 col-md-offset-3">
          <%= form_tag(channeluseradd_path, method: "get") do %>
            <div class="col-md-3">
              <%= label_tag(:q, "User List:") %>
            </div>
            <div class="col-md-5">
              <select name="userid">
                <%  @m_users.each do |wuser| %>
                  <% unless @c_users_id.include?(wuser['id']) %>
                    <option value="<%= wuser['id'] %>"><%= wuser["name"]%></option>
                  <% end %>
                <% end %>
              </select>
            </div>
              
            <div class="col-md-2">
              <%= submit_tag("Add", :class=> "btn btn-primary")%>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
      
    <% if @m_channelsids.include?session[:s_channel_id].to_i %>
      <hr>
    <% end %>
    <div>
      <div class="col-md-4" id="cuserlist">
      </div>

      <div class="col-md-2" >
        <p class="style22">ユーザ名</p> 
      </div>
      
      <div class="col-md-3">
        <p class="style23">メールアドレス</p>
      </div>

      <div class="col-md-3">
        <p class="style24" >セットアップ</p>
      </div>

      <% @m_channel_users.each do |c_user| %>
        <div class="col-md-4" id="cuserlist">
          <% if c_user['profile_image'].present? %>
              <img src="<%= c_user['profile_image'] %>" alt="Profile Image" class="profile-image" style="display: inline-block; margin-left: 250px; margin-top: 5px;">
          <% else %>
              <div class="profile-placeholder" style="display: inline-block; margin-left: 250px; margin-top: 5px;">
              <%= c_user['name'][0].upcase %>
              </div>
          <% end %>
        </div>

        <div class="col-md-2" >
          <p class="style22"><%= c_user['name']%></p> 
        </div>

        <div class="col-md-3">
          <p class="style23"><%= c_user['email']%></p>
        </div>

        <div class="col-md-3">
          <% if session[:current_user_id] == @created_admin[0]['userid'] %>
            <% if c_user['created_admin'] == false and @m_channelsids.include?session[:s_channel_id].to_i %>
              <p class="style24" ><%= link_to "Remove", channeluserdestroy_path(id: c_user['id'])%></p>
            <% end %>
          <% else %>
          <% end %>
        </div>
      <% end %>
    <div>
  </div>
</div>

<div>
  <%= render 'leftpanel/leftpanel' %>
</div>