config/routes.rb
Rails.application.routes.draw do
  root "static_pages#welcome"
  get "welcome" => "static_pages#welcome"

  get "workspace" => "m_workspaces#new"

  get "signin" => "sessions#new"
  post "signin" => "sessions#create"

  get "change_password" => "change_password#new"

  post "profile_upload" => "m_users#profile_upload"

  get "home" => "static_pages#home"

  get "memberinvite" => "member_invitation#new"
  post "memberinvite" => "member_invitation#invite"
  get "confirminvitation" => "m_users#confirm"

  get "channelcreate" => "m_channels#new"
  post "channelcreate" => "m_channels#create"

  get "channeledit" => "m_channels#edit"
  get "delete_channel" => "m_channels#delete"
  post "channelupdate" => "m_channels#update"

  get "star" => "t_direct_star_msg#create"
  get "unstar" => "t_direct_star_msg#destroy"
  get "starthread" => "t_direct_star_thread#create"
  get "unstarthread" => "t_direct_star_thread#destroy"

  get "delete_directmsg" => "direct_message#deletemsg"
  get "delete_directthread" => "direct_message#deletethread"

  get "delete_groupmsg" => "group_message#deletemsg"
  get "delete_groupthread" => "group_message#deletethread"

  get "groupstar" => "t_group_star_msg#create"
  get "groupunstar" => "t_group_star_msg#destroy"
  get "groupstarthread" => "t_group_star_thread#create"
  get "groupunstarthread" => "t_group_star_thread#destroy"

  get "starlists" => "star_lists#show"
  get "thread" => "thread#show"
  get "mentionlists" => "mention_lists#show"
  get "allunread" => "all_unread#show"
  get "draftlists" => "draft_lists#show"

  get "usermanage" => "user_manage#usermanage"
  get "edit" => "user_manage#edit"
  get "update" => "user_manage#update"

  get "channeluser" => "channel_user#show"
  get "channeluseradd" => "channel_user#create"
  get "channeluserdestroy" => "channel_user#destroy"
  get "channeluserleave" => "channel_user#leave"
  get "channeluserjoin" => "channel_user#join"

  post 'directmsg' => 'direct_message#show'
  post 'directthreadmsg' => 'direct_message#showthread'
  post 'directthreadmsgdirectly' => 'direct_message#showthreaddirectly'
  
  post 'groupmsg' => 'group_message#show'
  post 'groupthreadmsg' => 'group_message#showthread'
  post 'groupthreadmsgdirectly' => 'group_message#showthreaddirectly'

  get "refresh" => "sessions#refresh"

  get "refresh_direct" => "m_users#refresh_direct"
  get "refresh_group" => "m_channels#refresh_group"

  delete 'logout' =>  'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  
  # edit username
  get "useredit" => "m_users#edituser"
  patch "useredit" => "m_users#updateuser"

  # edit direct message
  get "/directmsg/edit/:id" => "direct_message#edit", as: "edit_directmsg"
  post "update_directmsg" => "direct_message#update"
  # edit direct thread
  get "/directthreadmsg/edit/:id" => "direct_message#edit_thread", as: "edit_directthreadmsg"
  post "update_directthreadmsg" => "direct_message#update_thread"
  # edit group message
  get "/groupmsg/edit/:id" => "group_message#edit", as: "edit_groupmsg"
  post "update_groupmsg" => "group_message#update"
  # edit group thread
  get "/groupthreadmsg/edit/:id" => "group_message#edit_thread", as: "edit_groupthreadmsg"
  post "update_groupthreadmsg" => "group_message#update_thread"

  # start routes for direct react
  post "directreact" => "t_direct_react_msg#create"
  get "directreact" => "t_direct_react_msg#create"

  post "directthreadreact" => "t_direct_react_thread#create"
  get "directthreadreact" => "t_direct_react_thread#create"
  # end routes for direct react

  # start routes for group react
  post "groupreact" => "t_group_react_msg#create"
  get "groupreact" => "t_group_react_msg#create"

  post "groupthreadreact" => "t_group_react_thread#create"
  get "groupthreadreact" => "t_group_react_thread#create"
  # end routes for group react

  resources :m_workspaces
  resources :m_users
  resources :m_channels
  resources :t_direct_messages
  resources :t_group_messages
end

app/views/direct_show/_edit.html.erb
<div id="main">
    <%= render "direct_show/directmsglists" %>
    <div class = "textboxbg">
      <div class="textboxeditor">

        <div id="toolbar">
          <button class="ql-bold"></button>
          <button class="ql-italic"></button>
          <button class="ql-strike"></button>
          <button class="ql-link"></button>
          <button class="ql-list" value="ordered"></button>
          <button class="ql-list" value="bullet"></button>
          <button class="ql-blockquote"></button>
          <button class="ql-code-block"></button>
          <button id="highlight-text" class="btn-icon"><i class="fas fa-laptop-code"></i></button>
        </div>

        <div id="link-dialog" style="display: none;">
          <h3 id= "link-title">Add your link</h3>
          <input type="text" id="link-name" placeholder="Enter link name">
          <input type="text" id="link-url" placeholder="Enter URL">
          <button id="link-cancel">Cancel</button>
          <button id="link-save">Yes</button>
        </div>

        <div class="editmsg">
          <%= form_for(:session, url: update_directmsg_path) do |f| %>
            <div class="col-md-10">
              <div id="editor"></div>
                <%= f.hidden_field :message, id: "quill-content" %>
                <%= hidden_field_tag :id, params[:id] %>
                <%= hidden_field_tag :action_type, "", id: "action-type" %>
            </div>
            <div class="col-md-1 mt-10 arrange">
              <%= f.submit "Send", class: "btn btn-primary sendbtn", id: "editsend" %>
              <button class="btn btn-secondary editcancle">Cancel</button>
            </div>
          <% end %>

        </div>

        <div class="col-md-11">
          <span><i class="fas fa-plus"></i></span>
          <button class="glyphicon glyphicon-font icon togglebtn" id="toggle-toolbar"></button>
        </div>
      </div>
    </div>
</div>

<div>
  <%= render "leftpanel/leftpanel" %>
</div>

<script>

  // highlight
  var Inline = Quill.import('blots/inline');

  class HighlightBlot extends Inline {
    static create(value) {
      let node = super.create();
      node.setAttribute('class', 'highlight');
      return node;
    }

    static formats(node) {
      return node.classList.contains('highlight') ? 'highlight' : undefined;
    }
  }

  HighlightBlot.blotName = 'highlight';
  HighlightBlot.tagName = 'span';
  HighlightBlot.className = 'highlight';
  Quill.register(HighlightBlot);

  //call quill
  document.addEventListener("DOMContentLoaded", function() {
    const toolbarOptions = [
      [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
      ['bold', 'italic', 'strike'],
      ['link'],
      [{ 'list': 'ordered'}, { 'list': 'bullet' }],
      ['blockquote','code-block'],
    ];

    const quill = new Quill('#editor', {
      modules: {
        toolbar: {
          container: '#toolbar',
          handlers: {
            link: function() {
              const range = quill.getSelection();
              if (range) {
                showLinkDialog(range);
              }
            }
          }
        }
      },
      placeholder: 'Type your message here ...',
      theme: 'snow'
    });

    // highlight start
    var isHighlighting = false;

    function updateButtonText() {
      if (isHighlighting) {
        document.querySelector('#highlight-text').classList.add('active');
      } else {
        document.querySelector('#highlight-text').classList.remove('active');
      }
    }

    function toggleHighlight() {
      var format = quill.getFormat();
      if (format.highlight) {
        quill.format('highlight', false);
        isHighlighting = false;
      } else {
        quill.format('highlight', true);
        isHighlighting = true;
      }
      updateButtonText();
      quill.focus();
    }

    quill.on('text-change', function() {
      var format = quill.getFormat();
      isHighlighting = !!format.highlight;
      updateButtonText();
    });

    document.querySelector('#highlight-text').addEventListener('click', function() {
      toggleHighlight();
      var htmlContent = quill.getSemanticHTML();
      document.querySelector('#quill-content').value = htmlContent;
    });

    updateButtonText();
    // highlight end 
        
    // highlight btn status 
    quill.container.firstChild.addEventListener('keydown', function(event) {
      if (event.key === 'Enter') {
        isHighlighting = false;
        updateButtonText();
      }
    });

    // for link dialog 
    var range = quill.getSelection();
    quill.on('selection-change', function(range, oldRange, source) {
      if (range && range.length > 0) {
        var selectedText = quill.getText(range.index, range.length);

        if (selectedText) {
          $('#toolbar').removeClass("hidden");
        }

        $('#link-name').val(selectedText);
      }
    });

    function showLinkDialog(range) {
      document.getElementById('link-dialog').style.display = 'block';
      document.getElementById('link-name').focus();
      document.getElementById('link-url').value = 'https://';
      document.getElementById('link-save').onclick = function() {
        const linkText = document.getElementById('link-name').value;
        const linkUrl = document.getElementById('link-url').value;
        if (linkText && linkUrl && range) {
        quill.insertText(range.index, linkText,'link',linkUrl);
          if (range.length > 0) {
            quill.deleteText(range.index + linkText.length, range.length);
          }
          quill.setSelection(range.index + linkText.length, 0);
          hideLinkDialog();
        }
      };

      document.getElementById('link-cancel').onclick = function() {
        hideLinkDialog();
      };
    }

    function hideLinkDialog() {
      document.getElementById('link-dialog').style.display = 'none';
      document.getElementById('link-name').value = '';
      document.getElementById('link-url').value = '';
    }

    // Prevent Quill from losing focus when clicking inside the dialog
    document.getElementById('link-dialog').addEventListener('mousedown', function(event) {
      event.stopPropagation();
    });

    // for toggle toolbar 
    const toolbar = quill.getModule('toolbar');
    const toolbarui = document.getElementById('toolbar');
    const toggleButton = document.getElementById('toggle-toolbar');

    toggleButton.addEventListener('click', function() {
      toolbarui.classList.toggle('hidden');
    });

    // get value 
    var form = document.querySelector('form');
    form.onsubmit = function() {
      var htmlContent = quill.getSemanticHTML();
      var quillContent = document.querySelector('#quill-content');
      htmlContent = htmlContent.replace(/<pre([^>]*)data-language="plain"([^>]*)>([\s\S]*?)<\/pre>/g, function(match, attr1, attr2, content) {
        content = content.trim().replace(/\n/g, '<br>');
        return `<div${attr1}class="ql-code-block"${attr2}>${content}</div>`;
      });
      htmlContent = htmlContent.replace(/<\/blockquote>\s*<blockquote>/g, '<br>');
      htmlContent = htmlContent.replace(/<\/p><p>/g, '<br>').replace(/<\/?p[^>]*>/g, '');
      quillContent.value = htmlContent;
    }

    // validate btn
    var sendbtn = document.querySelector(".sendbtn");
    sendbtn.disabled = true;
    quill.on('text-change', function(delta, oldDelta, source) {
      const editorContent = quill.getText().trim();
      if (editorContent.length > 0) {
        sendbtn.disabled = false;
      } else {
        sendbtn.disabled = true;
      }
    });

    // take value in text 
    // var data = '<%= j @data %>'
    var data = '<%= j @data.html_safe %>';
    data = data.replace(/<\/p><p>/g, '<pre>').replace(/<\/?p[^>]*>/g, '</pre>');
    console.log(data)
    // var data = '<p>Normal text <code>highlighted text</code></p>';
    quill.clipboard.dangerouslyPasteHTML(data);
    var tran = quill.root.innerHTML;
    // console.log(tran)
    console.log(data)
    var length = quill.getLength();
    quill.setSelection(length, length);

    // cancle btn 
    document.querySelector('.editcancle').addEventListener('click', function() {
      document.querySelector('#action-type').value = 'cancel';
    });

    document.querySelector('#editsend').addEventListener('click', function() {
      document.querySelector('#action-type').value = 'send';
    });

  });

</script>